export const ACTION_CONSTANTS = {
  // COUNTER ACTIONS
  COUNTER_INCREMENT_ACTION: 'INCREMENT',
  COUNTER_DECREMENT_ACTION: 'DECREMENT',
  COUNTER_CUSTOM_ACTION: 'CUSTOM_INCREMENT',
  COUNTER_CHANNEL_ACTION: 'CHANNEL_NAME',
  // POSTS ACTIONS
  POST_ADD_ACTION: '[POST PAGE] ADD POST',
};
